import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/Header";
import { ToastContainer } from "react-toastify";
import MarqueePage from "@/components/Marquee";

const notoSerifBangli = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});

export const metadata: Metadata = {
  title: "Bazar dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBangli.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderPage />
        <MarqueePage/>
        <main className="max-w-6xl mx-auto">{children}</main>
        <ToastContainer />
      </body>
    </html>
  );
}
